import "@/styles/globals.scss";

import SidebarArea from "@/components/Sidebar/SidebarArea";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import LoginPage from "@/components/AuthPage/AuthPage";

export default async function RootLayout({ children }) {
  let loggedIn = false;
  /// all login logic will be add soon...

  return (
    <html lang="en">
      <body>
        {loggedIn && (
          <>
            <SidebarArea />
            <main className="mainContent">{children}</main>
          </>
        )}
        {!loggedIn && <LoginPage />}
      </body>
    </html>
  );
}
