import '@/styles/globals.scss';

import SidebarArea from '@/components/Sidebar/SidebarArea';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SidebarArea />
        <main className='mainContent'>
          {children}
        </main>
        </body>
    </html>
  );
}
